language: node_js
node_js:
- "0.10"
- "4"
- "6"
before_script:
- export is_travis=true
deploy:
  provider: npm
  email: "sdk@qiniu.com"
  api_key:
    secure: O46FsywFgTyqwdf2tN5AXIJe3gnCjSHZT8tPfxl1TGY+p3iu0clixN8+nBvAqdnQvKu3Z4hmNhOd3zLdDbSsZoEWu6AhS+ySJWkkvM0rdIt9+wcVNWDyKd6WcW3bm1kq5KsLi1xM9VPfto5M/qYQRMg1RoCGDdxaAra4a6SH2Bs=
  on:
    tags: true
