language: node_js
node_js:
  - 0.8
  - 0.6
before_script:
  - export QINIU_ACCESS_KEY="8Y7uZY0cqHxAyGK27V_B2Bxf8IhAkqEPOHr6iwwc"
  - export QINIU_SECRET_KEY="1uvFVvk9IqFRQ6t4TCr-DdeXybTbSS0gauJrYiJN"
  - export QINIU_TEST_BUCKET="test963"
  - export QINIU_TEST_DOMAIN="test963.qiniudn.com"
